name: "Bug 反馈"
description: "功能无法使用或者行为不符合预期？"
title: "[Bug] "
labels: ["bug"]
body:

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 简单说说发生了什么？
      placeholder: 例如：发送某条指令后没有回复
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 如何复现
      description: bug 是如何被触发的？
      placeholder: |
        1. 在群里发送 xxx 指令
        2. 等待几秒
        3. 机器人没有任何反应
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: 其他信息
      description: 可以补充截图或其他相关信息
      placeholder: 例如：是否稳定触发？出现bug的频率？
    validations:
      required: false

  - type: textarea
    id: possible-solutions
    attributes:
      label: 可能的解决方案
      description: 如果有任何关于如何解决这个问题的想法，请在这里分享！
      placeholder: 例如：可能需要检查某个配置项，或者某个依赖版本不兼容
    validations:
      required: false
