name: "功能建议"
description: "有什么好点子？"
title: "[Feature] "
labels: ["enhancement"]
body:

  - type: textarea
    id: idea
    attributes:
      label: 你的想法
      description: 描述一下希望机器人能做什么？
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 功能必要性
      description: 这个功能能解决什么问题或带来什么好处？
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: 示例或参考
      description: 有没有类似功能的截图或其他机器人的例子？
      placeholder: 可以贴图片或者描述见过的类似功能
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: 补充说明
      description: 还有什么想说的？
    validations:
      required: false
