name: "功能优化"
description: "觉得现有功能可以做得更好？"
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        尽量填写下面的信息来更快解决问题！

  - type: textarea
    id: feature
    attributes:
      label: 哪个功能需要优化？
      description: 你觉得哪个功能可以做得更好？
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 现在有什么问题？
      description: 目前这个功能有什么让你觉得不够好用的地方？
      placeholder: 例如：某项功能误触频率过高/可以添加更多指令
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: 你希望怎么改进？
      description: 说说你觉得应该怎么优化？
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: 补充说明
      description: 还有什么需要补充的吗？
    validations:
      required: false
