name: "使用疑问"
description: "有任何关于Migut的问题？"
labels: ["question"]
body:

  - type: textarea
    id: question
    attributes:
      label: 你的问题
      description: 关于功能或Bot本身的问题都可以！
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 其他信息
      description: 随便写点吧~
    validations:
      required: false
