name: "使用疑问"
description: "有什么问题吗？"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        关于功能或Bot本身的问题都可以提！

  - type: textarea
    id: question
    attributes:
      label: 你的问题
      description: 有什么想问的？
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 其他信息
      description: 还有什么需要补充的吗？
    validations:
      required: false
